config/routes.rb
Rails.application.routes.draw do

  resources :users
  root 'static_pages#home'
  get 'home', to: 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, length: {maximum: 50},
                         uniqueness: true
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 254},
              format: {with: VALID_EMAIL_REGEX},
              uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
            if user
                log_in user
                redirect_to user
            else
                flash.now[:danger] = "Invalid username/email"
                render :new, status: :unprocessable_entity
        end
    end

    def destroy
        log_out
        redirect_to root_url
        puts current_user
    end
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def home
    end

    def about
    end

    def contact
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
    end
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        puts "Params received: #{user_params.inspect}"
        if @user.save
            redirect_to @user
            flash[:success] = 'User was successfully registered.'
          else
            render :new, status: :unprocessable_entity
          end
    end
    
    private
    def user_params
        params.require(:user).permit(:username, :email)
    end

    def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless @user == current_user
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def label_class
        "block text-sm font-medium leading-6 text-gray-900"
    end
    def input_class
        "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
    end
    def form_button_class
        "flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def log_in(user)
        session[:user_id] = user.id
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

    def logged_in?
        !current_user.nil?
    end

    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="flex content-center items-center justify-between w-full p-4">
    <ul class="flex flex-row list-none">
      <li><%= link_to "Home", home_path %></li>
    </ul>
    <div>
      <ul class="flex flex-row list-none gap-2">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <% if logged_in? %>
          <li><%= button_to "Log out", logout_url, method: :delete %></li>
          <li><%= link_to @current_user.username, user_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Sign In", login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-white">
  <head>
    <title>ToyAppV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="h-full">
    <%= render "layouts/header" %>
    <main class="container mx-auto px-4">
      <% flash.each do |message_type, message| %>
        <div class="<%= message_type == 'danger' ? 'bg-red-400' : message_type ==  'success' ? 'bg-green-500' : 'bg-emerald-300' %> text-center w-full">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="flex flex-col gap-4">
    <div class="bg-red-300 text-center">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul class="list-disc">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>ABOUT PAGE</h1>

app/views/static_pages/contact.html.erb
<h1>CONTACT PAGE</h1>

app/views/static_pages/home.html.erb
<div class="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
  <div class="text-center">
    <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">Welcome to the Toy App</h1>
    <p class="mt-6 text-lg leading-8 text-gray-600">Here you can post your toy collections, and check out other people's collections as well. Enjoy!</p>
    <div class="mt-10 flex items-center justify-center gap-x-6">
      <%= link_to "Sign Up Here", signup_path, class:"rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      <%= link_to "Learn More →", about_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<!--
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/fs'),
    ],
  }
  ```
-->
<!--
  This example requires updating your template:

  ```
  <html class="h-full bg-white">
  <body class="h-full">
  ```
-->
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Create an account</h2>
  </div>
  <div>
    <%= render 'shared/error_messages' %>
  </div>
  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <div class="space-y-6">
      <%= form_for(@user) do |f| %>
        <div>
          <%= f.label :username, class: label_class %>
          <div class="mt-2">
            <%= f.text_field :username, class: input_class %>
          </div>
        </div>
        <div>
          <%= f.label :email, class: label_class %>
          <div class="mt-2">
            <%= f.email_field :email, class: input_class %>
          </div>
        </div>
        <div class="mt-2">
          <%= f.submit 'Register', class: form_button_class %>
        </div>
      <% end %>
    </div>
    <p class="mt-10 text-center text-sm text-gray-500">
      Already a member?
      <%= link_to 'Login Here', login_path, class:"font-semibold leading-6 text-indigo-600 hover:text-indigo-500" %>
    </p>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <h1><%= @user.username%></h1>
</div>